/*
 *
 * LinkContractsPage constants
 *
 */

export const LOAD_LINKCONTRACTREQUESTS = 'app/LinkContractsPage/LOAD_LINKCONTRACTREQUESTS';
export const LOAD_LINKCONTRACTREQUESTS_SUCCESS = 'app/LinkContractsPage/LOAD_LINKCONTRACTREQUESTS_SUCCESS';
export const SEND_LINKCONTRACT_REQUEST = 'app/LinkContractsPage/SEND_LINKCONTRACT_REQUEST';
export const SEND_LINKCONTRACT_REQUEST_SUCCESS = 'app/LinkContractsPage/SEND_LINKCONTRACT_REQUEST_SUCCESS';
export const ACCEPT_LINKCONTRACT_REQUEST = 'app/LinkContractsPage/ACCEPT_LINKCONTRACT_REQUEST';
export const ACCEPT_LINKCONTRACT_REQUEST_SUCCESS = 'app/LinkContractsPage/ACCEPT_LINKCONTRACT_REQUEST_SUCCESS';
export const DECLINE_LINKCONTRACT_REQUEST = 'app/LinkContractsPage/DECLINE_LINKCONTRACT_REQUEST';
export const DECLINE_LINKCONTRACT_REQUEST_SUCCESS = 'app/LinkContractsPage/DECLINE_LINKCONTRACT_REQUEST_SUCCESS';

export const LOAD_LINKCONTRACTS = 'app/LinkContractsPage/LOAD_LINKCONTRACTS';
export const LOAD_LINKCONTRACTS_SUCCESS = 'app/LinkContractsPage/LOAD_LINKCONTRACTS_SUCCESS';
export const SEARCH_LINKCONTRACTS = 'app/LinkContractsPage/SEARCH_LINKCONTRACTS';
export const DELETE_LINKCONTRACT = 'app/LinkContractsPage/DELETE_LINKCONTRACTS';
export const DELETE_LINKCONTRACT_SUCCESS = 'app/LinkContractsPage/DELETE_LINKCONTRACTS_SUCCESS';

export const LOAD_PROFILES = 'app/LinkContractsPage/LOAD_PROFILES';
export const LOAD_PROFILES_SUCCESS = 'app/LinkContractsPage/LOAD_PROFILES_SUCCESS';
