/*
 *
 * App constants
 *
 */

export const SAVE_CREDENTIALS = 'app/App/SAVE_CREDENTIALS';
export const CLEAR_CREDENTIALS = 'app/App/CLEAR_CREDENTIALS';
export const CLEAR_CREDENTIALS_SUCCESS = 'app/App/CLEAR_CREDENTIALS_SUCCESS';
export const CLEAR_CREDENTIALS_ERROR = 'app/App/CLEAR_CREDENTIALS_ERROR';
export const RECEIVE_APP_ERROR = 'app/App/RECEIVE_APP_ERROR';
export const SHOW_APP_ERROR = 'app/App/SHOW_APP_ERROR';
export const CLEAR_APP_ERROR = 'app/App/CLEAR_APP_ERROR';
export const CLICK_ON_SEND_TO_LEADERBOARD = 'app/App/CLICK_ON_SEND_TO_LEADERBOARD';
export const SEND_TO_LEADER_BOARD_SUCCESS = 'app/App/SEND_TO_LEADER_BOARD_SUCCESS';
