/*
 *
 * App constants
 *
 */

export const SAVE_CREDENTIALS = 'app/App/SAVE_CREDENTIALS';
export const CLEAR_CREDENTIALS = 'app/App/CLEAR_CREDENTIALS';
export const CLEAR_CREDENTIALS_SUCCESS = 'app/App/CLEAR_CREDENTIALS_SUCCESS';
export const CLEAR_CREDENTIALS_ERROR = 'app/App/CLEAR_CREDENTIALS_ERROR';
